FROM node:18-alpine AS builder

RUN mkdir -p /app && chown -R node:node /app

WORKDIR /app

USER node

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .

RUN chmod +x ./node_modules/.bin/tsc

RUN npm run build

FROM node:18-alpine

WORKDIR /app
RUN chown -R node:node /app

USER node

COPY --from=builder --chown=node:node /app/dist ./dist

COPY --chown=node:node package*.json ./

RUN npm ci --omit=dev

EXPOSE 8080

CMD ["npm", "run", "start"] 