FROM node:18-alpine AS builder

RUN mkdir -p /app && chown -R node:node /app

WORKDIR /app

USER node

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist

COPY package*.json ./

RUN npm ci --omit=dev

EXPOSE 8080

CMD ["npm", "run", "start"] 