FROM node:18-alpine AS builder

RUN mkdir -p /app && chown -R node:node /app

WORKDIR /app

USER node

COPY --chown=node:node package*.json ./
RUN npm i

COPY --chown=node:node . .

RUN chmod +x ./node_modules/.bin/tsc \
    && chmod +x ./node_modules/.bin/vite

RUN npm run build

# FROM node:18-alpine

# WORKDIR /app
# RUN chown -R node:node /app

# USER node

# COPY --from=builder --chown=node:node /app/dist ./dist

# COPY --chown=node:node package*.json ./

# RUN npm i

# EXPOSE 8080

# CMD ["npm", "run", "start"] 

FROM nginx:alpine

# COPY --from=builder /app/build /usr/share/nginx/html
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]