server {
    listen 80;
    server_name intune.nextcloudlab.com;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /user {
        proxy_pass http://api.intune.member.nextcloudlab.com:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /chat {
        proxy_pass http://api.intune.chat.nextcloudlab.com:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
} 